import { Emblema_One, Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import CustomAppBar from "@/components/CustomAppbar";
import { Provider } from "react-redux";
import { store } from "@/redux/store";
import ReduxLayout from "@/components/ReduxLayout";

const emblema = Emblema_One({
  weight: "400",
  subsets: ["latin"],
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "First Project",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={` ${emblema.className} ${geistSans.variable} ${geistMono.variable} ${geistSans.className}`}
      >
        <ReduxLayout>
          <CustomAppBar />
          {children}
        </ReduxLayout>
      </body>
    </html>
  );
}
